[package]
name = "rocket_contrib"
version = "0.0.8"
authors = ["Sergio Benitez <sb@sergio.bz>"]

[features]
default = ["json"]
json = ["serde", "serde_json"]
tera_templates = ["tera", "templates"]
handlebars_templates = ["handlebars", "templates"]

# Internal use only.
templates = ["serde", "serde_json", "lazy_static_macro", "glob"]
lazy_static_macro = ["lazy_static"]

[dependencies]
rocket = { path = "../lib/" }
log = "*"

# JSON and templating dependencies.
serde = { version = "*", optional = true }
serde_json = { version = "*", optional = true }

# Templating dependencies only.
handlebars = { version = "*", optional = true, features = ["serde_type"] }
glob = { version = "*", optional = true }
lazy_static = { version = "*", optional = true }

# Tera dependency
[dependencies.tera]
git = "https://github.com/SergioBenitez/tera"
branch = "array-get-filter"
optional = true
