[package]
name = "rocket_codegen"
version = "0.1.0-rc"
authors = ["Sergio Benitez <sb@sergio.bz>"]

[lib]
plugin = true

[dependencies]
rocket = { version = "0.1.0-rc", path = "../lib/" }
log = "^0.3"

[dev-dependencies]
compiletest_rs = "^0.2"
