[package]
name = "rocket_macros"
version = "0.0.6"
authors = ["Sergio Benitez <sb@sergio.bz>"]

[lib]
plugin = true

[dependencies]
rocket = { path = "../lib/" }
log = "*"
env_logger = "*"

[dev-dependencies]
compiletest_rs = "*"
